### PR TITLE
Fix Warning MSB8027 caused by duplicate source file names

### PR DESCRIPTION
**Pull request by FySystem**

### CODE REVIEW

**Comment by kobalicek** [comment]
Please can you elaborate why this is required?

**Comment by FySystem** [comment]
https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8027?view=vs-2022
Actually, it doesn’t affect the code much, just fixes the warning in MSVC

**Comment by kobalicek** [comment]
But when is this warning generated?

I have never seen this warning in any project. It almost looks like you have another string.cpp in your project, but I don't see how that's asmjit fault.

**Comment by FySystem** [comment]
I think asmjit conflicts with std::string, and my project doesn’t contain any string.cpp file

**Comment by FySystem** [comment]
I created a new project in vs2022, and the warning was triggered when I directly imported the cpp file and compiled it

**Comment by kobalicek** [comment]
If you have a clean project, only with asmjit, and it issues this warning, then I think this should be reported to Microsoft instead. I think in this case you really need to provide more details, because I would like to keep the source file naming consistent with the project.

For example this is a clean build in VS2022, on CI:

   https://github.com/asmjit/asmjit/actions/runs/6138551515/job/16655535796

I don't see any warning of this kind. And this is build with tests:

   https://github.com/asmjit/asmjit/actions/runs/6138551515/job/16655539800

I use AsmJit in other projects too and I have never seen this. It seems more like a problem with your msbuild file. I think `std::string` has nothing to do with this as you would have to be compiling C++ standard library with your project and use the same intermediate directory for both, which is very unlikely.

**Pull request closed without merging**
