### PR TITLE
Install dll in /bin

### PR DESCRIPTION
**Pull request by xantares**
This is the convention for mingw.

### CODE REVIEW

**Comment by kirbyfan64** [comment]
It may the convention for MinGW, but this installs it for every platform, and this definitely isn't convention on Linux...

**Comment by xantares** [comment]
no, the behavior remains the same on unix, so/dylib are installed into /lib.

**Comment by kobalicek** [comment]
Just to clarify, this patch makes sure that .dll libs use RUNTIME DESTINATION instead of LIBRARY DESTINATION on Windows? Seems sane, I just never used cmake to install things on Windows.

**Comment by xantares** [comment]
Previously both RUNTIME, ARCHIVE and LIBRARY component were set to /lib, now RUNTIME is set ot /bin which allows to install properly dlls, also ARCHIVE has to be specified to install the corresponding import lib (.lib with msvc or .dll.a on mingw) in /lib.

**Comment by kobalicek** [comment]
Okay thanks for clarification, I will merge.

**Pull request merged**
