### PR TITLE
Fix warnings for MSVC

### PR DESCRIPTION
**Pull request by AndreasSchoenle**

### CODE REVIEW

**Comment by JohnSully** [comment]
It would be really nice to merge this.  Right now my header include looks like this:

#pragma warning(push, 0)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunknown-warning-option"
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wbool-operation"
#pragma GCC diagnostic ignored "-Wbool-compare"
#include "asmjit/asmjit.h"
#pragma GCC diagnostic pop
#pragma clang diagnostic pop
#pragma warning(pop)

Not very user friend for Werror users.

**Comment by kobalicek** [comment]
I did it differently, in 
  https://github.com/asmjit/asmjit/commit/c2f50e6fc52696099ae43f999a8f438eb1eca836

Let me know whether this fixes all of the issues you were having

**Comment by JohnSully** [comment]
Confirmed it works for MSVC and clang with my current set of warnings.  If GCC fails I'll post an issue.

Thanks!

**Comment by kobalicek** [comment]
Ok cool, thanks guys!

**Pull request closed without merging**
